# Generated by Django 2.0.9 on 2019-05-09 15:10

from django.db import migrations
import extra_apps.DjangoUeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=extra_apps.DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
