# Generated by Django 2.1.7 on 2019-05-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '验证码', 'verbose_name_plural': '验证码'},
        ),
    ]
